#!/bin/bash

MAUDE="/Users/cbraga/Applications/Alpha115/maude-Yices2.darwin64"
BMAUDE_DIR="/Users/cbraga/Dropbox/BMaude-project/urucu-amarela/"

if [ ! -x $MAUDE ]; then
    echo "$MAUDE does not exist or is not executable."
    echo "Please set the environment variable MAUDE."
    exit 1
fi

if [ ! -d "${BMAUDE_DIR}" ]; then
    echo "Please set BMAUDE_DIR to your local BMaude installation."
    exit 1
fi

if [ "$1" = "demo" ]; then
   $MAUDE -no-banner $BMAUDE_DIR/bmaude-no-banner.maude demo/demo.bmaude | less -R
else
  if [ "$1" = "demo-md" ]; then
     $MAUDE -no-banner $BMAUDE_DIR/bmaude-no-banner.maude demo/demo-md.bmaude
  else
    if [ "$TERM_PROGRAM" = "iTerm.app" ] ;
    then
      ./imgcat bmaude.jpg
      if [ "$1" != "" ]; then
         $MAUDE -no-banner $BMAUDE_DIR/bmaude-no-banner.maude "$1"
      else
         $MAUDE -no-banner $BMAUDE_DIR/bmaude-no-banner.maude
      fi
    else
      if [ "$1" != "" ]; then
         $MAUDE -no-banner $BMAUDE_DIR/bmaude-banner.maude "$1"
      else
         $MAUDE -no-banner $BMAUDE_DIR/bmaude-banner.maude
      fi
   fi
 fi
fi
