<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>B Maude Syntax; version 0.1
	The Regexp for the "Terminator" is:
		/(?&lt;=[\s\]\)\}])(\.)/
	The Regexp to stop in front of the "Terminator":
		/(?&lt;=[\s\]\)\}])(?=\.)/
	The Regexp for a simple "Identifier" is:
		/(`.|[^`,\(\)\[\]\{\}])+/
    Based on the Maude bundle.
	</string>
	<key>fileTypes</key>
	<array>
		<string>bmaude</string>
	</array>
	<key>name</key>
	<string>BMaude</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#base</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#command</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>base</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.maude</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.maude</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.maude</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.maude</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?\d+(/\d+|(\.\d+)?([eE]-?\d+(\.\d+)?)?)?)\b</string>
					<key>name</key>
					<string>constant.numeric.bmaude</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.bool.bmaude</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(MACHINE|VARIABLES|CONSTANTS|VALUES|OPERATIONS|IF|THEN|ELSE|END|WHILE|DO|BEGIN|OR)\b</string>
					<key>name</key>
					<string>keyword.control.bmaude</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(~|=|;|,|:=|\||\+|\*|/|-|where|and|&lt;&gt;|\[\]|\|=|-&gt;|\\)</string>
					<key>name</key>
					<string>keyword.operator.maude</string>
				</dict>
			</array>
		</dict>
		<key>command</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.command.system.maude</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(say|in|load|q(uit)?|eof|popd|pwd|cd|pushd|ls)\b\s*(.*)$</string>
					<key>name</key>
					<string>meta.command.system.maude</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.command.system.maude</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(say)\b\s*(.*)$</string>
					<key>name</key>
					<string>meta.command.say.bmaude</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.command.system.maude</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(view|search|mc|exec(n)?|sexec)\b</string>
					<key>name</key>
					<string>meta.command.bmaude</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=^|\s)\*{3}\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.maude</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.maude</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.triple-star.maude</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=^|\s)-{3}\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.maude</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.maude</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.triple-dash.maude</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=\*{3})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.maude</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\*{3}</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.maude</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.triple-star.maude</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=-{3})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.maude</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>-{3}</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.maude</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.triple-dash.maude</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment-content</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-content</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bmaude</string>
	<key>uuid</key>
	<string>BC5191D5-BA3A-4884-9DB0-ED3B22BABFD9</string>
</dict>
</plist>
